name: CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Nox
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cargo
            target/
          key: ${{ runner.os }}-${{ hashFiles('Cargo.toml', 'noxfile.py', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Set up Nox
        uses: wntrblm/nox@449f9352f26eb6465c0f0c7e6d89810e087f6f26 # 2025.10.14
        with:
          python-versions: '3.13'
      - name: Run tests and report coverage
        run: |
          nox --report nox.json
      - name: Create job summary
        if: always()
        uses: airtower-luna/nox-report-to-job-summary@v1.0.0
        with:
          report: nox.json
